docker run -it --rm \
   --network=pg-network  \
   -e POSTGRES_USER="root"   \
   -e POSTGRES_PASSWORD="root"   \
   -e POSTGRES_DB="ny_taxi"   \
   -v ny_taxi_postgres_data:/var/lib/postgresql   \
   -p 5432:5432 \
   postgres:18

docker run -it \
  -e PGADMIN_DEFAULT_EMAIL="admin@admin.com  \
  -e PGADMIN_DEFAULT_PASSWORD="root"  \
  -v pgadmin_data:/var/lib/pgadmin \
  -p 8085:80 \
  --network=pg-network  \
  dpage/pgadmin4

    